# Page settings
baseurl = ""
title = "Ultranet Communication Nepal"
keywords = "internet service provider in Karve"
languageCode = "en-us"
theme = "hugo-elate-theme"
logo = "logo.png"

[permalinks]
  post = "/:year/:month/:title/"

[params]

  custom_css = [ "css/modified-custom1.css", "css/modified-custom2.css" ]
  googleMapsApiKey = "AIzaSyAEOcPGx2ufv6fIOMt8pylCw3IjVCoveBw"

  # Meta
  author = "Ultranet"
  description = "Reliable and affordable internet service provider in Karve district, offering high quality internet to speed up browsing experieces and increase business productivities."
  email = "info@ultranet.com.np"

  # Navigation
  [params.navigation]
    brand = "Ultranet"
    home = "Plans"
    work = "IPTV"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # Add custom links before or after the default links
    # Assign a weight to define the order

  #prepended links
#  [[menu.prepend]]
#    url = "/plans/"
#    name = "Plans"
#    weight = 10

    # postpended links
  #[[menu.postpend]]
  #  url = ""
  #  name = "Login"
  #  weight = 10

  #  url = ""
  #  name = "Sign Up"
  #  weight = 20

  # Hero section
  [params.hero]
    subtitle = "immerse in Fast Internet experience"
    title = "Ultranet"

  # Intro section
  # Available icons: https://pagellapolitica.it/static/plugins/line-icons
  [params.intro]

  [[params.intro.item]]
    title = "11Mbps + IPTV"
    description = "Rs 3450 for 3 months"
    url = "http://eepurl.com/dKQY02"
    target = "_blank"
    button = "Online Exclusive"
    icon = "icon-magic-wand"
    img = "online-exclusive.jpg"

  [[params.intro.item]]
    title = "6Mbps + IPTV"
    description = "Rs 600/month for 12 months"
    url = "http://eepurl.com/dKQY02"
    target = "_blank"
    button = "Fibre for Student"
    icon = "icon-eyeglass"
    img = "student-fibre.jpg"

  [[params.intro.item]]
    title = "11Mbps + IPTV"
    description = "Rs 900/month for 12 months"
    url = "http://eepurl.com/dKQY02"
    target = "_blank"
    button = "Fibre for Home"
    icon = "icon-home"
    img = "home-fibre.jpg"

  [[params.intro.item]]
    title = " "
    description = "Rs 1100/month for 12 months"
    url = "http://eepurl.com/dKQY02"
    target = "_blank"
    button = "Fibre for Startup"
    icon = "icon-bulb"
    img = "startup-fibre.jpg"

  [[params.intro.item]]
    title = "33Mbps + IPTV"
    description = "Rs 1300/month for 12 months"
    url = "http://eepurl.com/dKQY02"
    target = "_blank"
    button = "Fibre for Cafe"
    icon = "icon-cup"
    img = "cafe-fibre.jpg"

  [[params.intro.item]]
    title = "44Mbps + IPTV"
    description = "Rs 1500/month for 12 months"
    url = "http://eepurl.com/dKQY02"
    target = "_blank"
    button = "Fibre for Business"
    icon = "icon-briefcase"
    img = "business-fibre.jpg"


# Intro Item Templates
#  [[params.intro.item]]
#    title = ""
#    description = ""
#    url = "#"
#    button = ""
#    icon = ""
#    img = ""

  [params.intro.video]
    enable = true
    title = "How to Sign Up and Install?"
    icon = "icon-control-play"
    url = "https://vimeo.com/293834164"
    #url = "https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Fultranetcommunication%2Fvideos%2F303404846920739%2F&show_text=0&width=700"


  # Work section
  [params.work]
    enable = true
    title = "The Non-stop Experience"
    description = "Get great Entertainment from the world popular TV channels and watch 'em all in High Definition"
    footertext = ""

  [[params.work.row]]
    img = "axn.jpg"
    alt = "Fear Factor Poster"
    title = "AXN Channel"
    subtitle = ""

  [[params.work.row]]
    img = "zing.jpg"
    alt = "Billo Poster"
    title = "Zing Channel"
    subtitle = ""

  [[params.work.row]]
    img = "cartoonnetwork.jpg"
    alt = "Pokemon Poster"
    title = "Cartoon Network Channel"
    subtitle = ""

  [[params.work.row]]
    img = "hbo.jpg"
    alt = "The Game of Thrones Poster"
    title = "HBO Channel"
    subtitle = ""

  [[params.work.row]]
    img = "natgeo.jpg"
    alt = "Life Below Zero Paster"
    title = "National Geographic Channel"
    subtitle = ""

  [[params.work.row]]
    img = "sonyespn.jpg"
    alt = "Sunday NFL Countdown Poster"
    title = "Sony ESPN Channel"
    subtitle = ""

  [[params.work.row]]
    img = "cnn.jpg"
    alt = "CNN Heroes Poster"
    title = "CNN Channel"
    subtitle = ""

  [[params.work.row]]
    img = "zoom.jpg"
    alt = "Kabali Poster"
    title = "Zoom Channel"
    subtitle = ""

  [[params.work.row]]
    img = "mtv.jpg"
    alt = "Teen Wolf Poster"
    title = "MTV Music Channel"
    subtitle = ""

  [[params.work.row]]
    img = "sonymax.jpg"
    alt = "American Next Top Model Poster"
    title = "Sony Max Channel"
    subtitle = ""

  [[params.work.row]]
    img = "cctv.jpg"
    alt = "Emperor in the Palace Poster"
    title = "CCTV Channel"
    subtitle = ""

  [[params.work.row]]
    img = "tlc.jpg"
    alt = "The Voice America Poster"
    title = "Channel V"
    subtitle = ""

  [[params.work.row]]
    img = "starworld.jpg"
    alt = "Sherlock Poster"
    title = "BBC Channel"
    subtitle = ""

  [[params.work.row]]
    img = "disneychannel.jpg"
    alt = "Lilo and Sticth Poster"
    title = "Disney Channel"
    subtitle = ""

  [[params.work.row]]
    img = "fox.jpg"
    alt = "Once Upon A Time Poster"
    title = "Starworld Channel"
    subtitle = ""

  [[params.work.row]]
    img = "diva.jpg"
    alt = "Queen of South Poster"
    title = "Fox Channel"
    subtitle = ""

  [[params.work.row]]
    img = "abc.jpg"
    alt = "What Would You Do Poster"
    title = "FX Channel"
    subtitle = ""

  [[params.work.row]]
    img = "animal-planet.jpg"
    alt = "Too Cute Poster"
    title = "Animal Planet Channel"
    subtitle = ""

  [[params.work.row]]
    img = "hbofamily.jpg"
    alt = "Laws and Orders Special Victim Unit Poster"
    title = "HBO Family Channel"
    subtitle = ""

  [[params.work.row]]
    img = "warnertv.jpg"
    alt = "The Good Place Poster"
    title = "Warner TV Channel"
    subtitle = ""

  [[params.work.row]]
    img = "discovery.jpg"
    alt = "Sherpa Poster"
    title = "Discovery Channel"
    subtitle = ""

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = ""

    [[params.testimonials.item]]
      quote = "Just had installation earlier this morning. The guy was very professional and the connection was active as soon as he'd finished. Currently experiencing download speeds even quicker than is advertised! Great experience so far."
      person = 'Session <span class="subtext">Aasha Tamrakar Homestay</span>'
      img = "person1.jpg"
      alt = "Session Tamrakar"

    [[params.testimonials.item]]
      quote = "Best broadband installation I have ever had, so easy no waiting around Subesh was on time, worked quickly and when i had a small problem later on that evening he helped me to sort it straight away! Didn't even have to ring customer services and wait on hold for ages :) Thanks very much Subesh, great customer service!"
      person = 'Priyanka <span class="subtext">University of Kathmandu</span>'
      img = "person2.jpg"
      alt = "Priyanka"

    [[params.testimonials.item]]
      quote = "After some time trying to get my phone line working I received a call from Situ and in no time at all the issue was identified and resolved. Situ was brilliant, he clearly has a wealth of experience trouble shooting. Thank you Situ and Ultranet"
      person = 'Raj <span class="subtext">Hotel Manager</span>'
      img = "person3.jpg"
      alt = "Raj"


  # Services section
  [params.services]
    enable = true
    title = "The Future is Fibre"
    description = "Forget copper! As broadband demands increase with technological advancements, fibre optics are the new standard for higher network speeds, stability and quality."

    [[params.services.item]]
      title = "Full HD Enjoyment"
      description = "On fibre broadband, it takes only minutes for a full HD movie to finish downloading, and the increased rate means you can even stream shows to watch while they download. No more having to suffer the buffer!"
      icon = "icon-screen-desktop"

    [[params.services.item]]
      title = "Turbo Internet Speed"
      description = "Light travels faster, no questions about that. Since optic fibres transmit light, they can deliver much higher speeds than copper cables. A 100% fibre optic connection allows us to ensure that you get the speeds you subscribe to."
      icon = "icon-speedometer"

    [[params.services.item]]
      title = "Seamless Internet Calls"
      description = "Fibre broadband has the capacity to handle heavier demand on your bandwidth, so video calls on a fibre connection are clearer and more seamless. You might as well be talking to the person through a window!"
      icon = "icon-earphones-alt"

    [[params.services.item]]
      title = "Smooth Online Gaming"
      description = "Connection speed, denoted in megabits per second (Mbps), has become critical in order to be an accomplished player. With fibre broadband speeds currently in the hundreds and still climbing, users can enjoy minimal lag and a smooth connection – every gamer’s dream."
      icon = "icon-game-controller"

    [[params.services.item]]
      title = "Better Stability"
      description = "Fibre optics is much less susceptible to environmental factors such as temperature and electromagnetic interference. In addition, attenuation is lower with fibre optics as well. This translates to a more stable connection for you."
      icon = "icon-energy"

      [[params.services.item]]
      title = "Security Performance"
      description = "Fibre optic cables transmit data via light, they are much less susceptible to outside interference (no more network issues during rainy days) and much more reliable. You can shop to your heart’s content and not worry about your money disappearing into the black holes of the Internet."
      icon = "icon-shield"


  # About section
  [params.about]
    enable = false
    title = "Our Team"
    description = "Ultranet management team believes in Future-proof technology so we chose to implement the 100% fibre optics cables from end to end, unlike service providers who use a combination of copper and fibre optics. On top of that, we know our network infrastructure well to ensure the quality of the service we deliver to you."

    [[params.about.item]]
      name = "Subesh Tamrakar"
      position = "Chief Executive Officer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      img = "ceo.jpg"
      alt = "CEO"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Ramhmi Shrestha"
      position = "Chief Marketing Officer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      img = "cmo.jpg"
      alt = "CMO"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Lossion Tamrakar"
      position = "Chief Technology Officer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      img = "cto.jpg"
      alt = "CTO"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Why Choose Us?"
    background = "counter_background.jpg"

    [[params.counters.item]]
      description = "Downloading K/b"
      icon = "icon-cloud-download"
      from = 0
      to = 59000
      interval = 50
      speed = 3000

    [[params.counters.item]]
      description = "Uploading K/b"
      icon = "icon-cloud-upload"
      from = 0
      to = 56000
      interval = 40
      speed = 3000

    [[params.counters.item]]
      description = "Subscribers"
      icon = "icon-users"
      from = 0
      to = 5000
      interval = 10
      speed = 3000

    [[params.counters.item]]
      description = "Coverage areas"
      icon = "icon-target"
      from = 0
      to = 18
      interval = 5
      speed = 3000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in Touch"
    description = "We're ready to help you! Leave your contact details and we will call you back within 24 hours."

    details = [
        ["icon-compass", 'Panauti Road, Banepa, Kavrepalanchok, Nepal'],
        ["icon-phone", '<a href="callto:00977011662729">+977011662729</a>'],
        ["icon-bubble", '<a href="http://wa.me/9779801116704">+9779801116704</a>'],
        ["icon-envelope", '<a href="mailto:info@ultranet.com.np">info@ultranet.com.np</a>'],
        ["icon-globe", "https://ultranet.com.np"]
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; 2018 Ultranet Communication Nepal. All Rights Reserved.'
    links = [
        ["icon-social-facebook", "https://facebook.com/ultranetcommunication"],
        ["icon-social-twitter", "https://twitter.com/ultranetcommunication"],
        ["icon-social-instagram", "https://instagram.com/ultranetcommunication"],
        ["icon-social-youtube", "https://youtube.com/user/ultranetcommunication"]
      ]
